# Generated by Django 3.2 on 2021-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_text', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(blank=True, verbose_name='date entered')),
                ('mood_classification', models.IntegerField(blank=True)),
            ],
        ),
    ]
